stages:
  download:
    cmd: bash src/download.sh
    outs:
      - data/raw/

  preprocess:
    cmd: pip install pandas && python src/preprocess.py
    deps:
      - data/raw/
    outs:
      - data/preprocessed/

  feature-extract:
    cmd: python src/feature_extract.py && cat dvc.lock
    deps:
      - data/preprocessed/
    outs:
      - data/model_ready/

  train:
    cmd: nextflow run nf/train.nf -with-trace outputs/trace.txt -with-report outputs/report.html
    deps:
      - data/model_ready/
      - nf/train.nf
    outs:
      - outputs/

  report:
    cmd: ls outputs/ && python src/make_report.py
    deps:
      - outputs/metrics.json
    outs:
      - Report.MD
