stages:
  download:
    cmd: bash src/download.sh
    outs:
      - data/raw/

  preprocess:
    cmd: pip install pandas && python src/preprocess.py
    deps:
      - data/raw/
    outs:
      - data/preprocessed/

  feature-extract:
    cmd: python src/feature_extract.py
    deps:
      - data/preprocessed/
    outs:
      - data/model_ready/

  train:
    cmd: |
      mkdir -p .nflogs
      nextflow run nf/train.nf -with-trace nflogs/trace.txt -with-report nflogs/report.html
      ls -lh outputs/
      ls -lh .nflogs/

    deps:
      - data/model_ready/
      - nf/train.nf
    outs:
      - outputs/

  report:
    cmd: ls -l outputs/ && python src/make_report.py
    deps:
      - outputs/metrics.json
    outs:
      - Report.MD
